### ISSUE TITLE
(FIXED) UI doesnt load

### ISSUE THREAD

**Issue by msfkonsol** [fatesc/fates-esp#4]
Tried it using the esp command in fates admin, failed.
Console error:
![image](https://user-images.githubusercontent.com/86378183/168481809-09b1aa83-63bd-42fb-bb79-7a86e0833107.png)

Tried executing directly from synapse, nothing.

**Comment by fatesc** [comment]
try now

**Comment by msfkonsol** [comment]
cheers, working now

**Comment by ghost** [comment]
doesnt work again

**Comment by ghost** [comment]
it just says ui loaded and nothing happens only name esp and distance
