### ISSUE TITLE
UI doesn't show

### ISSUE THREAD

**Issue by Bigolechevy** [fatesc/fates-esp#5]
In the Roblox console it says "UI Loaded..." but the UI doesn't show on my screen. Happens in every game for me.

**Comment by killerof9ods** [comment]
whats ur discord

**Comment by fatesc** [comment]
go to [this](https://github.com/fatesc/fates-admin/issues/73#issuecomment-1133627645)

**Comment by Bigolechevy** [comment]
> whats ur discord

BigOleChevy#4273

**Comment by Bigolechevy** [comment]
> go to [this](https://github.com/fatesc/fates-admin/issues/73#issuecomment-1133627645)

still doesn't work for me.

**Comment by Bigolechevy** [comment]
> go to [this](https://github.com/fatesc/fates-admin/issues/73#issuecomment-1133627645)

thanks it works now.
